config/routes.rb
Rails.application.routes.draw do
 
root 'pages#home'

 resources :posts do 
resources :comments, only: [:create, :new]
end

 resources :users, only: [:create, :new]
 resources :users_sessions, only: [:create, :new]

resources :admins, only: [:create, :new, :destroy]
get 'admin' => 'admins#new'

resources :contacts, only: [:create, :new]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password

end

app/models/comment.rb
class Comment < ActiveRecord::Base
has_ancestry

belongs_to :post
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController


def new
end


def create
admin = Admin.find_by_email(params[:email])
if admin && admin.authenticate(params[:password])
session[:admin] = admin.id
	redirect_to root_path
else
	render 'new'
	end
end

def destroy
session[:admin] = nil
redirect_to root_path
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:edit, :update, :show, :destroy] 
before_action :authenticate_admin, except: [:show, :index]

  def show
  @comments_array =  []

@post.comments.arrange.each do |comment|
  @comments_array << comment[0]
end

  end

def edit
end

def new
 @post = Post.new
  end

  def index
  @posts = Post.limit(10) 
  end


def destroy
@post.destroy
redirect_to posts_path
end

def update
if @post.update(post_params)
  redirect_to @post
else
  render('edit')
end
end

 def create 
@post = Post.create(post_params)
if @post.save
	redirect_to @post
else
	render('new')
 end
end

private

def find_post
  @post = Post.find(params[:id])
end

def post_params
	params.require(:post).permit(:title, :content)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
@user = User.new
end

def create
@user = User.create(user_params)
if @user.save
session[:user_id] = @user.id
flash[:notice] = "Logged In"
redirect_to root_path
else
render 'new'	
end
end
	private

def user_params
params.require(:user).permit(:name, :email)
	end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_sessions_helper.rb
module UsersSessionsHelper
end

app/views/admins/new.html.erb
<%= form_tag admins_path, method: :post do %>

<%= label_tag :email %>
<br>
<%= email_field_tag :email %>
<br>
<%= label_tag :password %>
<br>
<%= password_field_tag :password %>
<br>
<%= submit_tag %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>

<% if admin? %>
<%= link_to "Logout", admin_path(current_admin), method: :delete %>
<% end %>


<ul>
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Articles", posts_path %></li>
<li><%= link_to "Email", new_contact_path %></li>

</ul>

<%= yield %>
<%= params %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>