config/routes.rb
Rails.application.routes.draw do
 
root 'pages#home'

 resources :posts do 
resources :comments, only: [:create, :new]
end

 resources :users, only: [:create, :new]
 resources :users_sessions, only: [:create, :new]

resources :admins, only: [:create, :new, :destroy]
get 'admin' => 'admins#new'

resources :contacts, only: [:create, :new]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password

end

app/models/comment.rb
class Comment < ActiveRecord::Base
has_ancestry

belongs_to :post
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController


def new
end


def create
admin = Admin.find_by_email(params[:email])
if admin && admin.authenticate(params[:password])
session[:admin] = admin.id
	redirect_to root_path
else
	render 'new'
	end
end

def destroy
session[:admin] = nil
redirect_to root_path
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


def current_user
 User.where(id: session[:user_id]).first
end

def current_admin
Admin.find(session[:admin])
end

def admin?
	session[:admin]
end


def authenticate_admin
	unless admin?
		redirect_to root_path
	end
end

helper_method :current_admin
helper_method :admin?

helper_method :current_user



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_post, only: [:create, :new]


def new
@comment = Comment.new(:parent_id => params[:parent_id])
end

def create
comment = Comment.create(comment_params)
comment.post_id = params[:post_id]
if comment.save
redirect_to @post
else
render 'new'
end
end

private

def find_post 
@post = Post.find(params[:post_id])
end

def comment_params
params.require(:comment).permit(:body, :parent_id)
end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


def new
@contact = Contact.new
end


def create

@contact = Contact.create(contact_params)


	#params[:name] = @contact.email
	#params[:email] = @contact.name


if @contact.save

	 Emailer.send_to_me(@contact.email, @contact.name, params[:content]).deliver
	flash[:notice] = "Sent email"
	redirect_to :back
else
	flash[:notice] = "error sending mail"
	redirect_to :back
end
end

private


def contact_params
params.require(:contact).permit(:name, :email)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:edit, :update, :show, :destroy] 
before_action :authenticate_admin, except: [:show, :index]

  def show
  @comments_array =  []

@post.comments.arrange.each do |comment|
  @comments_array << comment[0]
end

  end

def edit
end

def new
 @post = Post.new
  end

  def index
  @posts = Post.limit(10) 
  end


def destroy
@post.destroy
redirect_to posts_path
end

def update
if @post.update(post_params)
  redirect_to @post
else
  render('edit')
end
end

 def create 
@post = Post.create(post_params)
if @post.save
	redirect_to @post
else
	render('new')
 end
end

private

def find_post
  @post = Post.find(params[:id])
end

def post_params
	params.require(:post).permit(:title, :content)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
@user = User.new
end

def create
@user = User.create(user_params)
if @user.save
session[:user_id] = @user.id
flash[:notice] = "Logged In"
redirect_to root_path
else
render 'new'	
end
end
	private

def user_params
params.require(:user).permit(:name, :email)
	end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_sessions_helper.rb
module UsersSessionsHelper
end

app/views/comments/_comment.html.erb
<%# @comments_array.reverse.each do |comment, index| %>
<div class="box">
<p><%= comment.body 
%>
 <br>
<div class="reply_form_button">reply </div>
<div class="reply_form">
<%= form_for [@post, @post.comments.build ] do |f| %>
<p> comment </p>

<%= f.hidden_field :parent_id, :value =>  comment.id %>
<%= f.text_area :body%>
<br>
<%= f.submit %>
<% end %>
</div>

</p>
<div class="show_replies">show replies </div>
<div class="replies">
<p>
<% comment.descendants.reverse.each do |child| %>
<%= child.body %>
<br>
<%#= link_to "Reply"#, new_post_comment_path(post_id: @post, :parent_id => child) %> 
</p>

<% end %>
</div>

<%# end %>

app/views/comments/_comments.html.erb
<% @comments_array.reverse.each_with_index do |comment, index| %>
<div class="box">
<p><%= comment.body 
%>
 <br>
<div class="reply_form_button">reply </div>
<div class="reply_form">
<%= form_for [@post, @post.comments.build ] do |f| %>
<p> comment </p>

<%= f.hidden_field :parent_id, :value =>  comment.id %>
<%= f.text_area :body%>
<br>
<%= f.submit %>
<% end %>
</div>

</p>
<div class="show_replies">show replies </div>
<div class="replies">
<p>
<% comment.descendants.reverse.each do |child| %>
<%= child.body %>
<br>
<%#= link_to "Reply"#, new_post_comment_path(post_id: @post, :parent_id => child) %> 
</p>

<% end %>
</div>

<% end %>

<script src="javascript/posts.js"> </script>
<div id="a"> a div </div>

app/views/contacts/new.html.erb
<%= form_for @contact do |f| %>



<%= f.label :name %>
<br>
<%= f.text_field :name %>
<br>
<%= f.label :email %>
<br>
<%= f.email_field :email %>
<br>
<%= label_tag :content %>
<br>
<%= text_area_tag :content %>
<br>
<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Article</h1>

<%= form_for @post do |f| %>

<%= f.label :title %>
<br>
<%= f.text_field :title %>
 
 <br>
<p> use wrapper class as body example <b>.wrapper p {} </b> </p>
 <%= f.label :content %>
<br>
<%= f.text_area :content %>
<br>
<%= f.submit "Submit Article"%>
<% end %>
<%= link_to "Back", :back %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

<p><%= link_to post.title, post_path(post) %></p>

<% end %>
<% if admin? %>
<%= link_to "create article", new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1> New Article</h1>

<%= form_for @post do |f| %>

<%= f.label :title %>
<br>
<%= f.text_field :title %>
 
 <br>
<p> use wrapper class as body example <b>.wrapper p {} </b> </p>
 <%= f.label :content %>
<br>
<%= f.text_area :content %>
<br>
<%= f.submit "Submit Article"%>
<% end %>
<%= link_to "Back", :back %>

app/views/posts/show.html.erb
<div class="wrapper">
<%= @post.content.html_safe%>
</div>

<br>
<% if admin? %>
<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>
<%= link_to "Back", :back %>
<%= form_for [@post, @post.comments.build ] do |f| %>

Leave a Comment <br>
<%= f.text_area :body%>
<br>
<%= f.submit %>
<% end %>

<%= render @comments_array.reverse %>